### ISSUE TITLE
Docs list incorrect package name?

### ISSUE THREAD

**Issue by dirtybirdnj** [fromholdio/silverstripe-schedulable#2]
In the readme file the installation instructions say to run this command:

`composer require fromholdio/silverstripe-fulltext-filters`

Is this correct? I would expect it to be this instead

`composer require fromholdio/silverstripe-schedulable`

I tried installing / using both of these packages and couldn't get it to work either way

**Comment by dizzystuff** [comment]
Hi @dirtybirdnj - whoops! Yep, you're right, that's a typo. I've updated the readme, thanks. The `composer require fromholdio/silverstripe-schedulable` command is definitely the correct one. When you run that, is the trouble you're having related to #1 or are there other problems?

**Comment by dirtybirdnj** [comment]
No other problems! Thanks
